# Generated by Django 4.1.5 on 2023-02-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Auther',
            field=models.SmallIntegerField(choices=[(1, 'Reader'), (2, 'Auther')]),
        ),
    ]
