# Generated by Django 4.1.5 on 2023-01-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kk',
        ),
    ]
