# Generated by Django 4.1.5 on 2023-02-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_profile_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Auther',
            new_name='account_type',
        ),
    ]
