# Generated by Django 4.1.5 on 2023-01-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_delete_kk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='read',
            old_name='profile',
            new_name='user',
        ),
    ]
